spring.application.name=patrigod

spring.datasource.url=jdbc:mysql://localhost:33306/patrigod
spring.datasource.username=root
spring.datasource.password=copado

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect