spring.application.name=patrigod

spring.datasource.url=jdbc:mysql://localhost:33306/patrigod
spring.datasource.username=root
spring.datasource.password=copado

spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.deserialization.fail-on-unknown-properties=false

resend.api.key=re_WUevzQu6_22MWhkPCTjYXtgLdFNBmTwcr
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.model=mistral
