package com.patrigod.chat.application.impl;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.patrigod.chat.application.ChatOllamaUseCase;
import com.patrigod.shared.exception.messages.ErrorMessages;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class ChatOllamaUseCaseImpl implements ChatOllamaUseCase {

    @Value("${configuration.ollama.api}")
    private String OLLAMA_URL ;

    private final ObjectMapper objectMapper;

    private final RestTemplate restTemplate;


    /**
     *
     * 1. Validates that the prompt is not empty.
     * 2. Builds a system message (systemPrompt) that limits the model's responses to topics related to World Heritage Cities in Spain.
     * 3. Prepares the message structure for Ollama:
     *    - The first message is of type "system" with the system prompt.
     *    - The second message is of type "user" with the user's prompt.
     * 4. Creates a JSON object with the model, the "stream" flag (disabled), and the list of messages.
     * 5. Uses ObjectMapper to convert the Java object to a JSON String.
     * 6. Prepares the HTTP header to indicate that the content is JSON.
     * 7. Sends the POST request to Ollama using RestTemplate.
     * 8. If the response is successful, returns the response body from Ollama.
     * 9. If there is an error, returns the corresponding error message.
     *
     * @param body Map containing the fields "prompt" (required) and "model" (optional)
     * @return Response generated by the Ollama model or an error message
     */

    @Override
    public String chatOllama(Map<String, String> body) {
        String prompt = body.get("prompt");

        String model = body.getOrDefault("model", "llama3.2:3b");

        if (prompt == null || prompt.isBlank()) {
            return ErrorMessages.PROMPT_MISSING_ERROR;
        }
        String systemPrompt = "Eres un asistente experto en las Ciudades Patrimonio de la Humanidad en España. " +
                "Solo puedes responder sobre temas relacionados con estas ciudades. Si la pregunta no tiene relación, " +
                "indica amablemente que solo puedes responder sobre las ciudades patrimonio de la humanidad en España. " +
                "Si necesitas ayuda, estoy aquí para ello. Y habla en el idioma que te hablen por favor.";

        try {
            //construction of the JSON body for Ollama
            Map<String, Object> jsonBody = getStringObjectMap(model, systemPrompt, prompt);

            //I serialize the Java object to JSON
            String json = objectMapper.writeValueAsString(jsonBody);

            //I prepare the HTTP header
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);

            HttpEntity<String> request = new HttpEntity<>(json, headers);

            //I send the request to Ollama, and he will get a response
            ResponseEntity<String> response = restTemplate.postForEntity(OLLAMA_URL,
                    request,
                    String.class);

            if (response.getStatusCode().is2xxSuccessful() && response.getBody() != null) {
                return response.getBody();
            } else {
                return ErrorMessages.CALLING_OLLAMA_ERROR + response.getBody();
            }
        } catch (Exception e) {
            return ErrorMessages.CALLING_OLLAMA_ERROR + e.getMessage();
        }
    }

    private static Map<String, Object> getStringObjectMap(String model, String systemPrompt, String prompt) {
        Map<String, Object> jsonBody = new HashMap<>();
        jsonBody.put("model", model);
        jsonBody.put("stream", false);

        List<Map<String, String>> messages = new ArrayList<>();
        //system message
        Map<String, String> systemMessage = new HashMap<>();
        systemMessage.put("role", "system");
        systemMessage.put("content", systemPrompt);
        messages.add(systemMessage);
        //user message
        Map<String, String> userMessage = new HashMap<>();
        userMessage.put("role", "user");
        userMessage.put("content", prompt);
        messages.add(userMessage);

        jsonBody.put("messages", messages);
        return jsonBody;
    }
}
